enum TYPES {
  WALLET_REQUEST = 'WALLET_REQUEST',
  WALLET_SUCCESS = 'WALLET_SUCCESS',
  WALLET_FAILURE = 'WALLET_FAILURE',

  MONEY_SEND_REQUEST = 'MONEY_SEND_REQUEST',
  MONEY_SEND_SUCCESS = 'MONEY_SEND_SUCCESS'
}

export default TYPES
