#!/bin/bash
#
# Prepare virtual env to be possible run django.
#

set -e

QUIET=false
ASK=true
UPDATE=false

function step() {
  $QUIET && return 0
  echo -n "STEP: $@"
  result=0
  $ASK && while true ; do read -p ' [Yn] ' yn
    case $yn in
      ""|[Yy]*) result=0 ; break ;;
      [Nn]*) result=1 ; break ;;
      *) echo "Please answer yes or no." ;;
    esac
  done
  return $result
}

BASE_DIR=$PWD
ENV_DIR="${BASE_DIR}/.env"

step "Install pip and venv" &&
  sudo apt-get install -y python3-pip python3-venv

step "Prepare project environment" && {
  pushd "${BASE_DIR}"

  rm -rf "${ENV_DIR}"
  virtualenv --python=python3.6 "${ENV_DIR}"
  virtualenv --python=python3.6 --relocatable "${ENV_DIR}"
  source "${ENV_DIR}/bin/activate"
  python3.6 -m pip install -r requirements.txt

  popd
}
