enum TYPES {
  REG_REQUEST = 'REG_REQUEST',
  REG_SUCCESS = 'REG_SUCCESS',
  REG_FAILURE = 'REG_FAILURE',

  AUTH_REQUEST = 'AUTH_REQUEST',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILURE = 'AUTH_FAILURE',

  GET_USER_INFO = 'GET_USER_INFO',
  GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST',
  GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'
}

export default TYPES
