enum TYPES {
  TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST',
  TRANSACTIONS_SUCCESS_TABLE = 'TRANSACTIONS_SUCCESS_TABLE',
  TRANSACTIONS_SUCCESS_CHART = 'TRANSACTIONS_SUCCESS_CHART',
  TRANSACTIONS_FAILURE = 'TRANSACTIONS_FAILURE',

  EXPORT_FILE = 'EXPORT_FILE'
}

export default TYPES
